java_library(
    name = "intellij",
    srcs = glob(["*.java"]),
    deps = [
        "@maven//:org_clojure_clojure",
        "@maven//:org_clojure_core_specs_alpha",
        "@maven//:org_clojure_spec_alpha",

        "@maven//:cheshire_cheshire",
        "@maven//:com_cognitect_aws_api",
        "@maven//:com_cognitect_aws_endpoints",
        "@maven//:com_cognitect_aws_s3",
        "@maven//:lambdaisland_kaocha",
        "@maven//:uswitch_lambada",
        "@maven//:spyscope_spyscope",
    ],
)
